/********************************************************************
* GeneralSkimmerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error GeneralSkimmerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGeneralSkimmerDict();
extern void G__cpp_setup_inheritanceGeneralSkimmerDict();
extern void G__cpp_setup_typetableGeneralSkimmerDict();
extern void G__cpp_setup_memvarGeneralSkimmerDict();
extern void G__cpp_setup_globalGeneralSkimmerDict();
extern void G__cpp_setup_memfuncGeneralSkimmerDict();
extern void G__cpp_setup_funcGeneralSkimmerDict();
extern void G__set_cpp_environmentGeneralSkimmerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "GeneralSkimmer.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GeneralSkimmerDictLN_TClass;
extern G__linked_taginfo G__GeneralSkimmerDictLN_TBuffer;
extern G__linked_taginfo G__GeneralSkimmerDictLN_TMemberInspector;
extern G__linked_taginfo G__GeneralSkimmerDictLN_TObject;
extern G__linked_taginfo G__GeneralSkimmerDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__GeneralSkimmerDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__GeneralSkimmerDictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__GeneralSkimmerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GeneralSkimmerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GeneralSkimmerDictLN_TList;
extern G__linked_taginfo G__GeneralSkimmerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GeneralSkimmerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GeneralSkimmerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__GeneralSkimmerDictLN_TTree;
extern G__linked_taginfo G__GeneralSkimmerDictLN_TBranch;
extern G__linked_taginfo G__GeneralSkimmerDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__GeneralSkimmerDictLN_TSelector;
extern G__linked_taginfo G__GeneralSkimmerDictLN_GeneralSkimmer;
extern G__linked_taginfo G__GeneralSkimmerDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__GeneralSkimmerDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
